// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import DatepickerController from './datepicker_controller'
Stimulus.register('datepicker', DatepickerController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)